# Generated by Django 4.2.5 on 2024-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blink_blink_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blink',
            name='ear_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
