# Generated by Django 4.2.5 on 2024-01-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blink_ear_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blink',
            name='blink_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
