# Generated by Django 5.0 on 2024-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_one_time_login",
            field=models.BooleanField(default=False),
        ),
    ]
